[build]
  publish = ".vitepress/dist"
  command = "pnpm install && pnpm run build"

[build.environment]
  NODE_VERSION = "20.19.0"
  PNPM_VERSION = "10.16.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
